-- MySQL Script generated by MySQL Workbench
-- Tue Jan 21 23:34:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetcci_nk
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetcci_nk` ;

-- -----------------------------------------------------
-- Schema projetcci_nk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetcci_nk` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projetcci_nk` ;

-- -----------------------------------------------------
-- Table `projetcci_nk`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetcci_nk`.`users` ;

CREATE TABLE IF NOT EXISTS `projetcci_nk`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(250) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `userName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projetcci_nk`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetcci_nk`.`comments` ;

CREATE TABLE IF NOT EXISTS `projetcci_nk`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `author` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_fk_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`author`)
    REFERENCES `projetcci_nk`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projetcci_nk`.`stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetcci_nk`.`stats` ;

CREATE TABLE IF NOT EXISTS `projetcci_nk`.`stats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` INT NOT NULL DEFAULT '1',
  `deathcount` INT NOT NULL DEFAULT '0',
  `playtime` INT NULL DEFAULT NULL,
  `rank` INT NULL DEFAULT NULL,
  `power` INT NOT NULL DEFAULT '1',
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_fk_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `id_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetcci_nk`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
